# Funding for MusicPortal
# Supporting the search for universal intelligence in music

github: # Add your GitHub Sponsors username here
patreon: # Add your Patreon username here
open_collective: # Add your Open Collective project here
ko_fi: # Add your Ko-fi username here
custom: # Add custom funding links (e.g., Bitcoin address)

# Note: This project is about discovering truth, not making money.
# If you want to support it:
# 1. Upload diverse music
# 2. Contribute code
# 3. Validate findings
# 4. Share discoveries
#
# If you still want to donate:
# - Support server costs
# - Fund research papers
# - Enable full-time development
# - Help us reach the moonshot
